// <auto-generated />
namespace Hebony.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedpostingmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpostingmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202003021346136_added posting models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
